apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
type: Opaque
data:
  POSTGRES_DB: aWNlY3JlYW1fZGI=       # icecream_db (Base64 encoded)
  POSTGRES_USER: dXNlcm5hbWU=          # username (Base64 encoded)
  POSTGRES_PASSWORD: cGFzc3dvcmQ=      # password (Base64 encoded)
